version: '3'
services:
  chromium:
    build:
      context: ./
      dockerfile: Dockerfile
    shm_size: '1gb'
    ports:
      - '9222:9222'
  chromium_alternative:
    build:
      context: ./
      dockerfile: Dockerfile2
    shm_size: '1gb'
    ports:
      - '9222:9222'